# Generated by Django 4.2.7 on 2025-09-06 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entries', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_snippet', models.TextField()),
                ('sentiment_score', models.FloatField(validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('start_position', models.PositiveIntegerField()),
                ('end_position', models.PositiveIntegerField()),
                ('is_manual_edit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='categories.category')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='entries.entry')),
            ],
            options={
                'ordering': ['start_position'],
                'unique_together': {('entry', 'category', 'start_position', 'end_position')},
            },
        ),
    ]
