# Generated by Django 4.2.7 on 2025-09-07 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='insights_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude coordinate for the main place mentioned in this entry', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='entry',
            name='location_name',
            field=models.CharField(blank=True, help_text='Name of the main place mentioned in this entry', max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude coordinate for the main place mentioned in this entry', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
