# Generated by hand to add faces M2M to Entry

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0002_entry_insights_processed_entry_latitude_and_more"),
        ("faces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="faces",
            field=models.ManyToManyField(blank=True, related_name="entries", to="faces.face"),
        ),
    ]

