name: Backend Unit Tests

on:
  push:
    paths:
      - 'backend/**'
      - 'contracts/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'contracts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services: {}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests (pytest)
        env:
          DJANGO_SETTINGS_MODULE: mindjourney.settings_minimal
        run: |
          pytest -q
