name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - 'contracts/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'contracts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mindjourney
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Restore Pact contracts artifact
        uses: actions/download-artifact@v4
        with:
          name: pact-contracts
          path: ../contracts/pacts
        continue-on-error: true
      - name: Run tests (pytest)
        env:
          DJANGO_SETTINGS_MODULE: mindjourney.settings_minimal
          # Settings for default settings.py in case tests load it
          DB_NAME: mindjourney
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
        run: |
          pytest -q
