name: Deploy to DigitalOcean App Platform

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

jobs:
  deploy:
    if: github.repository != ''
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Trigger deployment
        env:
          DO_APP_ID: ${{ secrets.DO_APP_ID }}
        run: |
          if [ -z "$DO_APP_ID" ]; then
            echo "DO_APP_ID secret is not set" >&2
            exit 1
          fi
          doctl apps create-deployment "$DO_APP_ID" --wait
